### NumPy Experiements 

In [1]:
import numpy as np

# numpy examples
an_array = np.array([3, 33, 333])
print(type(an_array))

print(an_array.shape)
print(an_array[0], an_array[1], an_array[2])
an_array[0] = 888
print(an_array)

# rank 2 arrays (2 D arrays) and accessing arrays
another = np.array([[11, 12, 13], [21, 22, 21]])
print(another)
print(another.shape)
print(another[0, 0], another[0, 1])

# create arrays
ex1 = np.zeros((2, 2))
print(ex1)

# create an array filled with 9.0
ex2 = np.full((2, 2), 0.9)
print(ex2)

# eigon matrix
ex3 = np.eye(2, 2)
print(ex3)

# array of ones
ex4 = np.ones((1, 2))
print(ex4)

# array indexing - for querying
an_array = np.array([[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]])
s = an_array[:2, 1:3]
print(s)

row_rank1 = an_array[1, :]
print(row_rank1, row_rank1.shape)

row_rank2 = an_array[0:2, :]
print(row_rank2, row_rank2.shape)

col_rank1 = an_array[:, 1]
print(col_rank1, col_rank1.shape)  # note extra []

col_rank2 = an_array[:, 1:2]
print(col_rank2, col_rank2.shape)  # note extra []

# array indexing for modifying underline arrays
an_array = np.array([[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]])
col_indices = np.array([0, 1, 2, 0])
print(col_indices)

row_indices = np.arange(4)
print(row_indices)


<class 'numpy.ndarray'>
(3,)
3 33 333
[888  33 333]
[[11 12 13]
 [21 22 21]]
(2, 3)
11 12
[[0. 0.]
 [0. 0.]]
[[0.9 0.9]
 [0.9 0.9]]
[[1. 0.]
 [0. 1.]]
[[1. 1.]]
[[12 13]
 [22 23]]
[21 22 23 24] (4,)
[[11 12 13 14]
 [21 22 23 24]] (2, 4)
[12 22 32] (3,)
[[12]
 [22]
 [32]] (3, 1)
[0 1 2 0]
[0 1 2 3]


In [3]:
# pairing of row indieces and col indices
for row, col in zip(row_indices, col_indices):
    print(row, ',', col)

0 , 0
1 , 1
2 , 2
3 , 0


In [5]:
# boolean indexing
an_array = np.array([[11, 12],[21, 22], [31, 32]])
an_array

array([[11, 12],
       [21, 22],
       [31, 32]])

In [7]:
# filter, if each value is greater than 15
filter = (an_array > 15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [8]:
# select elements using flter
an_array[filter]

array([21, 22, 31, 32])

In [9]:
# short form
an_array[an_array > 15]

array([21, 22, 31, 32])

In [11]:
# adding a 100 to even values 
an_array[an_array % 2 == 0] += 100
an_array

array([[ 11, 212],
       [ 21, 222],
       [ 31, 232]])

In [12]:
# data types -- python assigns the data type
ex1 = np.array([11, 12])
ex1.dtype

dtype('int64')

In [13]:
ex2 = np.array([11.0, 12.0])
ex2.dtype

dtype('float64')

In [16]:
# we can also tell python which data type to use
ex3 = np.array([11, 21], dtype=np.int64)
ex3.dtype

dtype('int64')

In [21]:
# can force float into int
ex4 = np.array([11, 21], dtype=np.float64)
ex4.dtype


dtype('float64')

In [22]:

ex5 = np.array([11.1, 12.7], dtype=np.int64)
ex5.dtype

dtype('int64')

In [23]:
ex5

array([11, 12])

In [24]:
# arithmatic operations
x = np.array([[111, 112], [121, 122]], dtype=np.int)
y = np.array([[211.1, 212.1],[221.1, 222.1]], dtype=np.float64)
print(x)
print(y)


[[111 112]
 [121 122]]
[[211.1 212.1]
 [221.1 222.1]]


In [33]:
# add, sub, mul, div 
print(x + y)
print(np.add(x,y))
print(x - y)
print(np.subtract(x, y))
print(x*y)
print(np.multiply(x, y))
print(x / y)
print(np.divide(x, y))
print(np.sqrt(x))
print(np.exp(x)) # e ^ x

[[322.1 324.1]
 [342.1 344.1]]
[[322.1 324.1]
 [342.1 344.1]]
[[-100.1 -100.1]
 [-100.1 -100.1]]
[[-100.1 -100.1]
 [-100.1 -100.1]]
[[23432.1 23755.2]
 [26753.1 27096.2]]
[[23432.1 23755.2]
 [26753.1 27096.2]]
[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]
[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]
[[10.53565375 10.58300524]
 [11.         11.04536102]]
[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


In [34]:
# statistical operations
arr = 10 * np.random.randn(2, 5)
print(arr)

[[ 11.44112267 -13.18234987  -1.93323395  -2.96717049   3.55955313]
 [ -4.92677581 -13.62490726   2.69626024  16.80383028   0.05108676]]


In [35]:
# mean of all element
print(arr.mean())

-0.20825842884377804


In [36]:
# mean by row
print(arr.mean(axis = 1))

[-0.6164157   0.19989884]


In [38]:
# mean by column
print(arr.mean(axis = 0))

[  3.25717343 -13.40362857   0.38151315   6.9183299    1.80531994]


In [39]:
# sum of all elements
print(arr.sum())

-2.0825842884377805


In [40]:
# median
print(np.median(arr, axis = 1))

[-1.93323395  0.05108676]


In [41]:
# sorting 
unsorted = np.random.randn(10)
print(unsorted)

[ 0.49065493  0.79005426  0.24063051  0.91197027 -0.2414351  -1.04348764
  1.16030628 -1.14853832 -0.99853143 -0.58412347]


In [43]:
# create a copy and sort
sorted = np.array(unsorted)
sorted.sort()
print(sorted)

[-1.14853832 -1.04348764 -0.99853143 -0.58412347 -0.2414351   0.24063051
  0.49065493  0.79005426  0.91197027  1.16030628]


In [44]:
# inplace sorting
unsorted.sort()
print(unsorted)

[-1.14853832 -1.04348764 -0.99853143 -0.58412347 -0.2414351   0.24063051
  0.49065493  0.79005426  0.91197027  1.16030628]


In [45]:
# unique elements
array = np.array([1, 2, 1, 4, 2, 1, 4, 2])
print(np.unique(array))

[1 2 4]


In [46]:
# set operations
s1 = np.array(['desk', 'chair', 'bulb'])
s2 = np.array(['lamp', 'blub', 'chair'])
print(s1, s2)

['desk' 'chair' 'bulb'] ['lamp' 'blub' 'chair']


In [50]:
print(np.intersect1d(s1, s2))

['chair']


In [51]:
print(np.union1d(s1, s2)) 
print(np.setdiff1d(s1, s2))
print(np.in1d(s1, s2))

['blub' 'bulb' 'chair' 'desk' 'lamp']
['bulb' 'desk']
[False  True False]


In [52]:
# NumPy broadcasting
import numpy as np
start = np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [55]:
start1 = np.zeros([4,3])
print(start1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [56]:
add_rows = np.array([1, 0, 2])
print(add_rows)

[1 0 2]


In [59]:
# row wise addition
y = start + add_rows
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [61]:
add_cols = np.array([[0, 1, 2, 3]])
print(add_cols)
add_cols = add_cols.T
print(add_cols)

[[0 1 2 3]]
[[0]
 [1]
 [2]
 [3]]


In [62]:
# colum wise addition
y = start + add_cols
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [63]:
add_scalar = np.array(1)
print(add_scalar)
print(start + add_scalar)

1
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [66]:
# create a 3x4 matrix
A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [67]:
# create a 4x1 matrix
B = np.array([0,1,0,2])
print(B)

[0 1 0 2]


In [68]:
# add two using broadcasting
print(A + B)

[[ 1  3  3  6]
 [ 5  7  7 10]
 [ 9 11 11 14]]
