### NumPy Experiements 

In [1]:
import numpy as np

# numpy examples
an_array = np.array([3, 33, 333])
print(type(an_array))

print(an_array.shape)
print(an_array[0], an_array[1], an_array[2])
an_array[0] = 888
print(an_array)

# rank 2 arrays (2 D arrays) and accessing arrays
another = np.array([[11, 12, 13], [21, 22, 21]])
print(another)
print(another.shape)
print(another[0, 0], another[0, 1])

# create arrays
ex1 = np.zeros((2, 2))
print(ex1)

# create an array filled with 9.0
ex2 = np.full((2, 2), 0.9)
print(ex2)

# eigon matrix
ex3 = np.eye(2, 2)
print(ex3)

# array of ones
ex4 = np.ones((1, 2))
print(ex4)

# array indexing - for querying
an_array = np.array([[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]])
s = an_array[:2, 1:3]
print(s)

row_rank1 = an_array[1, :]
print(row_rank1, row_rank1.shape)

row_rank2 = an_array[0:2, :]
print(row_rank2, row_rank2.shape)

col_rank1 = an_array[:, 1]
print(col_rank1, col_rank1.shape)  # note extra []

col_rank2 = an_array[:, 1:2]
print(col_rank2, col_rank2.shape)  # note extra []

# array indexing for modifying underline arrays
an_array = np.array([[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]])
col_indices = np.array([0, 1, 2, 0])
print(col_indices)

row_indices = np.arange(4)
print(row_indices)


<class 'numpy.ndarray'>
(3,)
3 33 333
[888  33 333]
[[11 12 13]
 [21 22 21]]
(2, 3)
11 12
[[0. 0.]
 [0. 0.]]
[[0.9 0.9]
 [0.9 0.9]]
[[1. 0.]
 [0. 1.]]
[[1. 1.]]
[[12 13]
 [22 23]]
[21 22 23 24] (4,)
[[11 12 13 14]
 [21 22 23 24]] (2, 4)
[12 22 32] (3,)
[[12]
 [22]
 [32]] (3, 1)
[0 1 2 0]
[0 1 2 3]
